// Generated by Apple Swift version 5.5 (swiftlang-1300.0.31.1 clang-1300.0.29.1)
#ifndef QRGENERATOR_SWIFT_H
#define QRGENERATOR_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="QRGenerator",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class NSNumber;
@class NSString;

SWIFT_CLASS("_TtC11QRGenerator16MVISAMerchantTLV")
@interface MVISAMerchantTLV : NSObject
@property (nonatomic) BOOL isTipAvailable;
/// Tag 00 - version 01
@property (nonatomic, copy) NSString * _Nullable payloadFormatIndicator;
/// Tag 01 - version 01
@property (nonatomic, copy) NSString * _Nullable pointOfInitiation;
/// Tag 02 version 00 and 01
@property (nonatomic, copy) NSString * _Nullable mVisaMerchantID;
@property (nonatomic, copy) NSString * _Nullable mVisaMerchantPAN;
/// Tag 03 version 01
@property (nonatomic, copy) NSString * _Nullable aliasID;
/// Tag 04 - version 01
@property (nonatomic, copy) NSString * _Nullable masterCardPAN1;
/// Tag 05 - version 01
@property (nonatomic, copy) NSString * _Nullable masterCardPAN2;
/// Tag 06 - version 01
@property (nonatomic, copy) NSString * _Nullable npciid1;
/// Tag 07 - version 01
@property (nonatomic, copy) NSString * _Nullable npciid2;
/// Tag 08 - version 01
@property (nonatomic, copy) NSString * _Nullable tag08;
/// Tag 09 - version 01
@property (nonatomic, copy) NSString * _Nullable discover1;
/// Tag 10 - version 01
@property (nonatomic, copy) NSString * _Nullable discover2;
/// Tag 11 - version 01
@property (nonatomic, copy) NSString * _Nullable amex1;
/// Tag 12 - version 01
@property (nonatomic, copy) NSString * _Nullable amex2;
/// Tag 13 - version 01
@property (nonatomic, copy) NSString * _Nullable jcb1;
/// Tag 14 - version 01
@property (nonatomic, copy) NSString * _Nullable jcb2;
/// Tag 15 - version 01
@property (nonatomic, copy) NSString * _Nullable unionPay1;
/// Tag 16 - version 01
@property (nonatomic, copy) NSString * _Nullable unionPay2;
/// Tag 17 to 25 Reserved by EMVCo - version 01
@property (nonatomic, copy) NSString * _Nullable tag17;
@property (nonatomic, copy) NSString * _Nullable tag18;
@property (nonatomic, copy) NSString * _Nullable tag19;
@property (nonatomic, copy) NSString * _Nullable tag20;
@property (nonatomic, copy) NSString * _Nullable tag21;
@property (nonatomic, copy) NSString * _Nullable tag22;
@property (nonatomic, copy) NSString * _Nullable tag23;
@property (nonatomic, copy) NSString * _Nullable tag24;
@property (nonatomic, copy) NSString * _Nullable tag25;
/// Tag 26 to 51 Templates reserved for additional payment networks - version 01
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable tag26;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable tag27;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable tag28;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable tag29;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable tag30;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable tag31;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable tag32;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable tag33;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable tag34;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable tag35;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable tag36;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable tag37;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable tag38;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable tag39;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable tag40;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable tag41;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable tag42;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable tag43;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable tag44;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable tag45;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable tag46;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable tag47;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable tag48;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable tag49;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable tag50;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable tag51;
/// Tag 52 version 00 and 01
@property (nonatomic, copy) NSString * _Nullable merchantCategoryCode;
/// Tag 53 version 00 and 01
@property (nonatomic, copy) NSString * _Nullable currencyCode;
/// Tag 54 version 00 and 01
@property (nonatomic, copy) NSString * _Nullable transactionAmount;
/// Tag 55 version 00 and 01
@property (nonatomic, copy) NSString * _Nullable tipAndFeeIndicator;
/// Tag 56 version 00 and 01
@property (nonatomic, copy) NSString * _Nullable convenienceFeeAmount;
/// Tag 57 version 00 and 01
@property (nonatomic, copy) NSString * _Nullable convenienceFeePercentage;
/// Tag 58 version 00 and 01
@property (nonatomic, copy) NSString * _Nullable countryCode;
/// Tag 59 version 00 and 01
@property (nonatomic, copy) NSString * _Nullable merchantName;
/// Tag 60 version 00 and 01
@property (nonatomic, copy) NSString * _Nullable cityName;
/// Tag 61 - version 01
@property (nonatomic, copy) NSString * _Nullable postalCode;
/// Tag 62 - version 01 - Super tag
@property (nonatomic, copy) NSString * _Nullable additionalDataField;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable additionalDataFieldTemplate;
/// Tag 63 - version 01
@property (nonatomic, copy) NSString * _Nullable crc;
/// Tag 64 - version 01
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable merchantInformationLanguageTemplate;
/// Tag 65 to 79 RFU for EMVCo - version 01
@property (nonatomic, copy) NSString * _Nullable tag65;
@property (nonatomic, copy) NSString * _Nullable tag66;
@property (nonatomic, copy) NSString * _Nullable tag67;
@property (nonatomic, copy) NSString * _Nullable tag68;
@property (nonatomic, copy) NSString * _Nullable tag69;
@property (nonatomic, copy) NSString * _Nullable tag70;
@property (nonatomic, copy) NSString * _Nullable tag71;
@property (nonatomic, copy) NSString * _Nullable tag72;
@property (nonatomic, copy) NSString * _Nullable tag73;
@property (nonatomic, copy) NSString * _Nullable tag74;
@property (nonatomic, copy) NSString * _Nullable tag75;
@property (nonatomic, copy) NSString * _Nullable tag76;
@property (nonatomic, copy) NSString * _Nullable tag77;
@property (nonatomic, copy) NSString * _Nullable tag78;
@property (nonatomic, copy) NSString * _Nullable tag79;
/// Tag 80 to 99 Unreserved Templates - version 01
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable tag80;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable tag81;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable tag82;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable tag83;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable tag84;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable tag85;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable tag86;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable tag87;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable tag88;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable tag89;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable tag90;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable tag91;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable tag92;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable tag93;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable tag94;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable tag95;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable tag96;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable tag97;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable tag98;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable tag99;
/// Supported only in Version 00
@property (nonatomic, copy) NSString * _Nullable primaryID;
/// Supported only in Version 00
@property (nonatomic, copy) NSString * _Nullable secondaryID;
/// Tag 01 - version 01
@property (nonatomic, copy) NSString * _Nullable billID;
/// Tag 02 - version 01
@property (nonatomic, copy) NSString * _Nullable mobileNumber;
/// Tag 03 - version 01
@property (nonatomic, copy) NSString * _Nullable storeID;
/// Tag 04 - version 01
@property (nonatomic, copy) NSString * _Nullable loyaltyNumber;
/// Tag 05 - version 01
@property (nonatomic, copy) NSString * _Nullable referenceID;
/// Tag 06 - version 01
@property (nonatomic, copy) NSString * _Nullable consumerID;
/// Tag 07 - version 01
@property (nonatomic, copy) NSString * _Nullable terminalID;
/// Tag 08 - version 01
@property (nonatomic, copy) NSString * _Nullable purpose;
/// Tag 09 - version 01
@property (nonatomic, copy) NSString * _Nullable additionalConsumerDataRequest;
/// Tag 10 - version 01
@property (nonatomic, copy) NSString * _Nullable merchantTaxID;
/// Tag 11 - version 01
@property (nonatomic, copy) NSString * _Nullable merchantChannel;
@property (nonatomic, copy) NSString * _Nullable tagSixtyTwo10 SWIFT_DEPRECATED_MSG("This variable is deprecated in 3.1.0, use variable additionalDataFieldTemplate for related tag as key");
@property (nonatomic, copy) NSString * _Nullable addDataMasterCard1 SWIFT_DEPRECATED_MSG("This variable is deprecated in 3.1.0, use variable additionalDataFieldTemplate for related tag as key");
@property (nonatomic, copy) NSString * _Nullable addDataMasterCard2 SWIFT_DEPRECATED_MSG("This variable is deprecated in 3.1.0, use variable additionalDataFieldTemplate for related tag as key");
@property (nonatomic, copy) NSString * _Nullable addDataNpci1 SWIFT_DEPRECATED_MSG("This variable is deprecated in 3.1.0, use variable additionalDataFieldTemplate for related tag as key");
@property (nonatomic, copy) NSString * _Nullable addDataNpci2 SWIFT_DEPRECATED_MSG("This variable is deprecated in 3.1.0, use variable additionalDataFieldTemplate for related tag as key");
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11QRGenerator19MVisaPayMerchantTLV")
@interface MVisaPayMerchantTLV : MVISAMerchantTLV
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC11QRGenerator11QRCodeError")
@interface QRCodeError : NSObject
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull errorCodes;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class QRGeneratorResponse;

/// The QRCodeGenerator class provides sync and async methods to generate QR code string
/// all the available methods are class level.
/// To generate QR Code, call class method generateQRData: with required parameter.
SWIFT_CLASS("_TtC11QRGenerator15QRCodeGenerator")
@interface QRCodeGenerator : NSObject
/// Generate QR code string asynchronously from the dictionary provided. This will provide TLVString and error in completionHandler block.
/// \param qrCodeDictionary QR code data in map format.
///
/// \param completionHandler A block object containing the String tlv object and error code.
/// if qrCodeError key is not in output means generating is successfully done and tlvString will have the QR TLV.
/// If qrCodeError key is there in output means generator has failed with some error and qrCodeError key will provide json array of error codes.
///
+ (void)generateQRCodeStringWithQrCodeDictionary:(NSDictionary<NSString *, id> * _Nonnull)qrCodeDic completionHandler:(SWIFT_NOESCAPE void (^ _Nonnull)(QRGeneratorResponse * _Nullable))completionHandler;
/// Generate QR code string asynchronously from the dictionary provided. This will provide TLVString and error in completionHandler block.
/// <ul>
///   <li>
///     Return QRGeneratorResponse object with parsed data.
///     if qrCodeError key is not in output means generating is successfully done and tlvString will have the QR TLV.
///     If qrCodeError key is there in output means generator has failed with some error and qrCodeError key will provide json array of error codes.
///   </li>
/// </ul>
/// \param qrCodeDictionary QR code data in map format.
///
+ (QRGeneratorResponse * _Nonnull)generateQRCodeStringWithQrCodeDictionary:(NSDictionary<NSString *, id> * _Nonnull)qrCodeDic SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11QRGenerator9QRCodeTag")
@interface QRCodeTag : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull payloadFormatIndicator;)
+ (NSString * _Nonnull)payloadFormatIndicator SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull pointOfInitiation;)
+ (NSString * _Nonnull)pointOfInitiation SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull mVisaMerchantID;)
+ (NSString * _Nonnull)mVisaMerchantID SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull aliasID;)
+ (NSString * _Nonnull)aliasID SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull masterCardPAN1;)
+ (NSString * _Nonnull)masterCardPAN1 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull masterCardPAN2;)
+ (NSString * _Nonnull)masterCardPAN2 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull npciid1;)
+ (NSString * _Nonnull)npciid1 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull npciid2;)
+ (NSString * _Nonnull)npciid2 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag08;)
+ (NSString * _Nonnull)tag08 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull discover1;)
+ (NSString * _Nonnull)discover1 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull discover2;)
+ (NSString * _Nonnull)discover2 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull amex1;)
+ (NSString * _Nonnull)amex1 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull amex2;)
+ (NSString * _Nonnull)amex2 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull jcb1;)
+ (NSString * _Nonnull)jcb1 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull jcb2;)
+ (NSString * _Nonnull)jcb2 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull unionPay1;)
+ (NSString * _Nonnull)unionPay1 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull unionPay2;)
+ (NSString * _Nonnull)unionPay2 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag17;)
+ (NSString * _Nonnull)tag17 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag18;)
+ (NSString * _Nonnull)tag18 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag19;)
+ (NSString * _Nonnull)tag19 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag20;)
+ (NSString * _Nonnull)tag20 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag21;)
+ (NSString * _Nonnull)tag21 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag22;)
+ (NSString * _Nonnull)tag22 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag23;)
+ (NSString * _Nonnull)tag23 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag24;)
+ (NSString * _Nonnull)tag24 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag25;)
+ (NSString * _Nonnull)tag25 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag26;)
+ (NSString * _Nonnull)tag26 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag27;)
+ (NSString * _Nonnull)tag27 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag28;)
+ (NSString * _Nonnull)tag28 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag29;)
+ (NSString * _Nonnull)tag29 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag30;)
+ (NSString * _Nonnull)tag30 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag31;)
+ (NSString * _Nonnull)tag31 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag32;)
+ (NSString * _Nonnull)tag32 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag33;)
+ (NSString * _Nonnull)tag33 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag34;)
+ (NSString * _Nonnull)tag34 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag35;)
+ (NSString * _Nonnull)tag35 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag36;)
+ (NSString * _Nonnull)tag36 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag37;)
+ (NSString * _Nonnull)tag37 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag38;)
+ (NSString * _Nonnull)tag38 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag39;)
+ (NSString * _Nonnull)tag39 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag40;)
+ (NSString * _Nonnull)tag40 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag41;)
+ (NSString * _Nonnull)tag41 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag42;)
+ (NSString * _Nonnull)tag42 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag43;)
+ (NSString * _Nonnull)tag43 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag44;)
+ (NSString * _Nonnull)tag44 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag45;)
+ (NSString * _Nonnull)tag45 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag46;)
+ (NSString * _Nonnull)tag46 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag47;)
+ (NSString * _Nonnull)tag47 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag48;)
+ (NSString * _Nonnull)tag48 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag49;)
+ (NSString * _Nonnull)tag49 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag50;)
+ (NSString * _Nonnull)tag50 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag51;)
+ (NSString * _Nonnull)tag51 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull merchantCategoryCode;)
+ (NSString * _Nonnull)merchantCategoryCode SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull currencyCode;)
+ (NSString * _Nonnull)currencyCode SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull transactionAmount;)
+ (NSString * _Nonnull)transactionAmount SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tipAndFeeIndicator;)
+ (NSString * _Nonnull)tipAndFeeIndicator SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull convenienceFeeAmount;)
+ (NSString * _Nonnull)convenienceFeeAmount SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull convenienceFeePercentage;)
+ (NSString * _Nonnull)convenienceFeePercentage SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull countryCode;)
+ (NSString * _Nonnull)countryCode SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull merchantName;)
+ (NSString * _Nonnull)merchantName SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull cityName;)
+ (NSString * _Nonnull)cityName SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull postalCode;)
+ (NSString * _Nonnull)postalCode SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull additionalDataFieldTemplate;)
+ (NSString * _Nonnull)additionalDataFieldTemplate SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull billID;)
+ (NSString * _Nonnull)billID SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull mobileNumber;)
+ (NSString * _Nonnull)mobileNumber SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull storeID;)
+ (NSString * _Nonnull)storeID SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull loyaltyNumber;)
+ (NSString * _Nonnull)loyaltyNumber SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull referenceID;)
+ (NSString * _Nonnull)referenceID SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull consumerID;)
+ (NSString * _Nonnull)consumerID SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull terminalID;)
+ (NSString * _Nonnull)terminalID SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull purpose;)
+ (NSString * _Nonnull)purpose SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull merchantTaxID;)
+ (NSString * _Nonnull)merchantTaxID SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull merchantChannel;)
+ (NSString * _Nonnull)merchantChannel SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull additionalConsumerDataRequest;)
+ (NSString * _Nonnull)additionalConsumerDataRequest SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tagSixtyTwo10 SWIFT_DEPRECATED_MSG("This variable is deprecated in 3.1.0, use variable merchantTaxID for related tag as key");)
+ (NSString * _Nonnull)tagSixtyTwo10 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull addDataMasterCard1 SWIFT_DEPRECATED_MSG("This variable is deprecated in 3.1.0, use variable which is realted to tag as key");)
+ (NSString * _Nonnull)addDataMasterCard1 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull addDataMasterCard2 SWIFT_DEPRECATED_MSG("This variable is deprecated in 3.1.0, use variable which is realted to tag as key");)
+ (NSString * _Nonnull)addDataMasterCard2 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull addDataNpci1 SWIFT_DEPRECATED_MSG("This variable is deprecated in 3.1.0, use variable which is realted to tag as key");)
+ (NSString * _Nonnull)addDataNpci1 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull addDataNpci2 SWIFT_DEPRECATED_MSG("This variable is deprecated in 3.1.0, use variable which is realted to tag as key");)
+ (NSString * _Nonnull)addDataNpci2 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull crc;)
+ (NSString * _Nonnull)crc SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull merchantInformationLanguageTemplate;)
+ (NSString * _Nonnull)merchantInformationLanguageTemplate SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag65;)
+ (NSString * _Nonnull)tag65 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag66;)
+ (NSString * _Nonnull)tag66 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag67;)
+ (NSString * _Nonnull)tag67 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag68;)
+ (NSString * _Nonnull)tag68 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag69;)
+ (NSString * _Nonnull)tag69 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag70;)
+ (NSString * _Nonnull)tag70 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag71;)
+ (NSString * _Nonnull)tag71 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag72;)
+ (NSString * _Nonnull)tag72 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag73;)
+ (NSString * _Nonnull)tag73 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag74;)
+ (NSString * _Nonnull)tag74 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag75;)
+ (NSString * _Nonnull)tag75 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag76;)
+ (NSString * _Nonnull)tag76 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag77;)
+ (NSString * _Nonnull)tag77 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag78;)
+ (NSString * _Nonnull)tag78 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag79;)
+ (NSString * _Nonnull)tag79 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag80;)
+ (NSString * _Nonnull)tag80 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag81;)
+ (NSString * _Nonnull)tag81 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag82;)
+ (NSString * _Nonnull)tag82 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag83;)
+ (NSString * _Nonnull)tag83 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag84;)
+ (NSString * _Nonnull)tag84 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag85;)
+ (NSString * _Nonnull)tag85 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag86;)
+ (NSString * _Nonnull)tag86 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag87;)
+ (NSString * _Nonnull)tag87 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag88;)
+ (NSString * _Nonnull)tag88 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag89;)
+ (NSString * _Nonnull)tag89 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag90;)
+ (NSString * _Nonnull)tag90 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag91;)
+ (NSString * _Nonnull)tag91 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag92;)
+ (NSString * _Nonnull)tag92 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag93;)
+ (NSString * _Nonnull)tag93 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag94;)
+ (NSString * _Nonnull)tag94 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag95;)
+ (NSString * _Nonnull)tag95 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag96;)
+ (NSString * _Nonnull)tag96 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag97;)
+ (NSString * _Nonnull)tag97 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag98;)
+ (NSString * _Nonnull)tag98 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tag99;)
+ (NSString * _Nonnull)tag99 SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11QRGenerator7QRError")
@interface QRError : NSObject
@property (nonatomic, copy) NSString * _Nonnull errorCode;
@property (nonatomic, copy) NSString * _Nonnull errorDescription;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11QRGenerator19QRGeneratorResponse")
@interface QRGeneratorResponse : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable tlvString;
@property (nonatomic, readonly, strong) QRCodeError * _Nullable qrCodeError;
@property (nonatomic, readonly, copy) NSArray<QRError *> * _Nullable qrErrors;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif
